spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: strangedev505
    password: nnmoxsmunzocukuh
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace