spring:
  profiles:
    active: serve
  h2:
    console:
      enabled: true
  server:
    tomcat:
      max-http-post-size: 100MB
      max-swallow-size: 100MB
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: strangedev505
    password: nnmoxsmunzocukuh
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: debug
#    p6spy: info

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4= # 임의의 문자열을 Base64로 인코딩한 값
  refresh-token-validity-in-seconds: 1209600 # 14일
  access-token-validity-in-seconds: 43200 # 12시간

cloud:
  aws:
    credentials:
      access-key: AKIAWEYQVFMPLZ45LNXQ
      secret-key: 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
    s3:
      bucket: 505bucket
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false

file:
  dir: C:\Users\SSAFY\Desktop/file/

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

OPENVIDU_URL: https://ec2.unofficial.kr/
OPENVIDU_SECRET: STRANGE505

main: main

springdoc:
  swagger-ui:
    path: /api/swagger-ui
    use-root-path: true