spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/ssafy_test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 1000
    open-in-view: false
#        format_sql: true
#        use_sql_comments: true

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4= # 임의의 문자열을 Base64로 인코딩한 값
  refresh-token-validity-in-seconds: 1209600 # 14일
#  access-token-validity-in-seconds: 43200 # 12시간
  access-token-validity-in-seconds: 10 # 12시간

cloud:
  aws:
    credentials:
      access-key: AKIAWEYQVFMPLZ45LNXQ
      secret-key: 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
    s3:
      bucket: 505bucket
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false

file:
  dir: C:\Users\SSAFY\Desktop/file/

mail:
  base-url : "http://localhost:3000/verify?verificationCode="

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

test: test