spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
cloud:
  aws:
    credentials:
      access-key: {AKIAWEYQVFMPLZ45LNXQ}
      secret-key: {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}
    s3:
      bucket: 505bucket
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false